= Building The Linux Client =

:toc:
:toc-placement: preamble
:icons:

*This guide is for building the client manually. Doing so requires a reasonable
amount of knowledge about the system, for a basic installation we strongly
recommend link:admin.adoc#repacking-the-client-with-a-new-configuration[repacking].*

== Dependencies ==

First of all make sure your Ubuntu installation is up to date:
--------------------------------------------------------------------------------
sudo apt-get update
sudo apt-get upgrade
--------------------------------------------------------------------------------

GRR client requires Python 2.7 to build.

*Note that Python 2.6 is no longer supported*

On a Debian-based system install the following packages:
--------------------------------------------------------------------------------
apt-get install build-essential git-core debhelper python-dev python-dateutil dpkg-dev
--------------------------------------------------------------------------------

The link:quickstart.adoc[quickstart script] will get the following installed, if
you want to install them manually see the link:serverfromscratch.adoc[server
from scratch] instructions:

 - Patched version of M2Crypto 0.21.1
 - Protobuf 2.4.1 (http://code.google.com/p/protobuf/downloads/list)
 - Sleuthkit 3.2.3 (http://www.sleuthkit.org/sleuthkit/download.php)
 - Sleuthkit Python bindings (pytsk) (latest) (http://code.google.com/p/pytsk/downloads/list)
 - psutil 0.6.1 (at minimum 0.5.0) (http://code.google.com/p/psutil/)

=== Volatility ===

Volatility support is added when volatility is available on the build system, otherwise no-support is build into the client.

Grab a copy of the latest version of the scudette branch:
--------------------------------------------------------------------------------
svn checkout http://volatility.googlecode.com/svn/branches/scudette/ volatility
--------------------------------------------------------------------------------

To build volatility:
--------------------------------------------------------------------------------
python setup.py build
--------------------------------------------------------------------------------

To install volatility:
--------------------------------------------------------------------------------
sudo python setup.py install
--------------------------------------------------------------------------------

Remove the windows plugins since they add distorm3 as a dependency:
--------------------------------------------------------------------------------
sudo rm -r /usr/local/lib/python2.7/dist-packages/volatility-3.0_tp1-py2.7.egg/volatility/plugins/windows/
--------------------------------------------------------------------------------

And remove the following line:
--------------------------------------------------------------------------------
from volatility.plugins import windows
--------------------------------------------------------------------------------

From the file:
--------------------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/volatility-3.0_tp1-py2.7.egg/volatility/plugins/__init__.py
--------------------------------------------------------------------------------

=== Building the client ===

Once you have all dependencies installed, set up a build directory.

--------------------------------------------------------------------------------
> mkdir /usr/local/grr_build
--------------------------------------------------------------------------------

Alternatively, you might also use another directory and edit the build_root in the config file.

=== PyInstaller ===
Grab a copy of the latest version of PyInstaller (version 2.1 should work for sure) and put it in the build directory.
--------------------------------------------------------------------------------
git clone -b develop git://github.com/pyinstaller/pyinstaller.git

> ls /usr/local/grr_build/pyinstaller/pyinstaller.py 
/usr/local/grr_build/pyinstaller/pyinstaller.py

> python /usr/local/grr_build/pyinstaller/pyinstaller.py --version
2.1

--------------------------------------------------------------------------------


== GRR ==

Get a copy of the GRR source:
--------------------------------------------------------------------------------
> git clone https://code.google.com/p/grr/
--------------------------------------------------------------------------------

=== Configuration ===

For more details see ClientConfiguration.

If you want to build a proper .deb package, you need to make sure that you have server keys available (and readable) in /etc/grr/server.local.yaml

--------------------------------------------------------------------------------
> sudo grep key /etc/grr/server.local.yaml

PrivateKeys.driver_signing_private_key: -----BEGIN RSA PRIVATE KEY-----
Client.executable_signing_public_key: -----BEGIN PUBLIC KEY-----
PrivateKeys.ca_key: -----BEGIN PRIVATE KEY-----
Client.driver_signing_public_key: -----BEGIN PUBLIC KEY-----
PrivateKeys.server_key: -----BEGIN PRIVATE KEY-----
PrivateKeys.executable_signing_private_key: -----BEGIN RSA PRIVATE KEY-----
--------------------------------------------------------------------------------

You may also just build a template without keys and later repack it on the installed server.

=== Build ===

The build command generates a template for your client (that doesn't have keys or a customized name yet) like the one you can download from the GRR page directly:

--------------------------------------------------------------------------------
> PYTHONPATH=. python grr/client/client_build.py --config=grr/config/grr-server.yaml build

> ls grr/executables/linux/templates/grr-client_*.zip
grr/executables/linux/templates/grr-client_2.9.1.1_amd64.zip

--------------------------------------------------------------------------------

=== Deploy ===

In order to make a proper .deb package, the keys have to be installed as well. The deploy command does this for you:

--------------------------------------------------------------------------------
> PYTHONPATH=. python grr/client/client_build.py --config=grr/config/grr-server.yaml deploy

> ls grr/executables/linux/installers/
grr_2.9.1.1_amd64.changes  grr_2.9.1.1_amd64.deb
--------------------------------------------------------------------------------


== Troubleshooting ==

=== PyInstaller build ===

Add the --log-level=DEBUG parameter

To check if a certain module is included in the PyInstaller archive:
--------------------------------------------------------------------------------
python ../pyinstaller/utils/ArchiveViewer.py dist/grrd
--------------------------------------------------------------------------------

=== No module named pkg_resources ===
When testing the client binary I get:
--------------------------------------------------------------------------------
ImportError: No module named pkg_resources
--------------------------------------------------------------------------------

Check for "pkg_resources" being included in either M2Crypto or protobuf and remove any instance from the file.

E.g. just remove the line:
--------------------------------------------------------------------------------
__import__("pkg_resources").declare_namespace(__name__)
--------------------------------------------------------------------------------

in the following files:
--------------------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/protobuf-2.4.1-py2.7.egg/google/__init__.py
/usr/local/lib/python2.7/dist-packages/protobuf-2.4.1-py2.7.egg/google/protobuf/__init__.py
--------------------------------------------------------------------------------

If that does not work try removing the files:
--------------------------------------------------------------------------------
rm /usr/local/lib/python2.7/dist-packages/protobuf-2.4.1-py2.7.egg/google/__init__.py*
rm /usr/local/lib/python2.7/dist-packages/protobuf-2.4.1-py2.7.egg/google/protobuf/__init__.py*
--------------------------------------------------------------------------------

Extract the egg:
--------------------------------------------------------------------------------
cd /usr/local/lib/python2.7/dist-packages/
mv protobuf-2.4.1-py2.7.egg protobuf-2.4.1-py2.7.egg.zip
mkdir protobuf-2.4.1-py2.7.egg
cd protobuf-2.4.1-py2.7.egg
unzip ../protobuf-2.4.1-py2.7.egg.zip
rm ../protobuf-2.4.1-py2.7.egg.zip
--------------------------------------------------------------------------------

in the following files:
--------------------------------------------------------------------------------
/usr/local/lib/python2.7/dist-packages/protobuf-2.4.1-py2.7.egg/google/__init__.py
/usr/local/lib/python2.7/dist-packages/protobuf-2.4.1-py2.7.egg/google/protobuf/compiler/__init__.py
--------------------------------------------------------------------------------

=== No module named google ===
When testing the client binary I get:
--------------------------------------------------------------------------------
ImportError: No module named google
--------------------------------------------------------------------------------

This mean you've removed too much from the protobuf Python bindings.

=== No attribute FileDescriptor ===
When testing the client binary I get:
--------------------------------------------------------------------------------
AttributeError: 'module' object has no attribute 'FileDescriptor'
--------------------------------------------------------------------------------

Make sure you're using protobuf 2.4.1 and don't have an older version on the system that is used instead.

=== No module named __m2crypto ===
This applies to older versions of Pyinstaller.

Check if __m2crypto gets imported as "__m2crypto" and not as "M2Crypto.__m2crypto":
--------------------------------------------------------------------------------
../pyinstaller/utils/ArchiveViewer.py dist/grrd
--------------------------------------------------------------------------------

See the section about M2Crypto in the link:serverfromscratch.adoc[server
from scratch] instructions for more information.
