Publications
------------

link:https://drive.google.com/open?id=0B1wsLqFoT7i2c3FHOHNjOFpmdjA[A scalable file based data store for forensic analysis], by Flavio Cruz, Andreas Moser, Michael Cohen. DFRWS 2015 Europe.

link:https://googledrive.com/host/0B9hc84IflFGbN2IwMTUyYTUtMTU0Mi00ZWQ3LWFhNDktM2IyMTg5MmY3OWI0/Hunting%20in%20the%20Enterprise:%20Forensic%20Triage%20and%20Incident%20Response[Hunting in the enterprise: Forensic triage and incident response], by Moser,
Andreas, and Michael I. Cohen. Digital Investigation, 2013.

link:http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/37237.pdf[Distributed forensics and incident response in the enterprise], by M.I. Cohen,
D. Bilby, G. Caronni. Digital Investigation, 2011.

Presentations
-------------

link:https://drive.google.com/open?id=0B1wsLqFoT7i2MEltRFp1Zzk1Rkk[GRR Meetup: API Edition] @ Nov 2015 GRR Meetup by G. Castle and M. Bushkov. Covers API basics and discusses where we are headed with API dev.

link:https://drive.google.com/open?id=0B1wsLqFoT7i2S2ZoY1pOYm4ybDA[GRR Hunting Best Practices] @ Oct 2015 GRR Meetup by G. Castle.

link:https://drive.google.com/open?id=0B1wsLqFoT7i2RTVaR1o1eHJYcjA&authuser=0[Tactical use of GRR Artifacts, Fuse, Plaso and Timesketch] by D. Bilby link:https://www.youtube.com/watch?v=JciAp0uB7AY[Demo Video (youtube)]

"link:https://drive.google.com/file/d/0B1wsLqFoT7i2NnI5dkdScHlrWVU/view?usp=sharing[Intro to GRR]" for the Open Source Network Security Monitoring Group @ UIUC Feb 2015. link:https://www.youtube.com/watch?v=ZAXtCMspgY0[Video] by G. Castle

"link:https://drive.google.com/file/d/0B1wsLqFoT7i2Z2pxM0wycS1lcjg/edit?usp=sharing[GRR: Find all the badness, collect all the things]" @ Blackhat 2014 link:http://www.youtube.com/watch?v=DudGrSv26NY[Video] by G.
Castle. Also presented link:https://youtu.be/eLehQ3QmdEA[a 20 min version of the same talk] for link:https://www.concise-courses.com/past/[Hacker Hotshots].

link:https://googledrive.com/host/0B1wsLqFoT7i2N3hveC1lSEpHUnM/Docs/GRR%20Rapid%20Response%20-%20OSFC%202012.pdf[OSDFC 2012 GRR Overview], by D. Bilby

Workshops
---------

DFRWS US 2015 Workshop link:https://drive.google.com/open?id=0B1wsLqFoT7i2akRmeWlsZHF2ck0[slides] and link:https://github.com/destijl/grr-workshop-setup[scripts to setup your own workshop infrastructure] by G. Castle.

DFRWS EU 2015 Workshop link:https://drive.google.com/file/d/0B1wsLqFoT7i2NjRCN1c3TXdwUUU/view?usp=sharing[workshop slides] by A. Moser

OSDF 2013 link:https://drive.google.com/?usp=chrome_app#folders/0B1wsLqFoT7i2eU1jU0JldW9JUU0[workshop presentation] and link:osdf2013workshop.adoc[materials] by D. Bilby.

Podcasts
--------

GRR Rapid Response on link:http://podcast.wh1t3rabbit.net/dtr-episode-98-grr-grr-rapid-response-0[Down the Security Rabbithole] Jun 2014 by G. Castle.

Whitepapers
-----------

link:https://drive.google.com/file/d/0B1wsLqFoT7i2U3M1X0k5aVFkXzQ/edit?usp=sharing[GRR Forensic Artifacts White Paper], by G. Castle

External Presentations
----------------------

These are presentations about GRR by people outside the core GRR team.

"link:https://github.com/pidydx/slides/blob/master/HumanHunting.pdf[Human Hunting]" @BSidesSF 2015 by Sean Gillespie. Covers how Yahoo is using GRR. link:https://www.youtube.com/watch?v=4qCvx3SnAm4[Video].

"link:http://kernsec.org/files/lss2015/GRR.pdf[GRR Rapid Response: Remote Live Forensics for Incident Response]" @ link:http://kernsec.org/wiki/index.php/Linux_Security_Summit_2015[Linux Security Summit] Aug 2015 by Sean Gillespie.
