Publications
------------

link:https://storage.googleapis.com/docs.grr-response.com/scalable_datastore.pdf[A scalable file based data store for forensic analysis], by Flavio Cruz, Andreas Moser, Michael Cohen. DFRWS 2015 Europe.

link:https://storage.googleapis.com/docs.grr-response.com/MoserCohenHunting.pdf[Hunting in the enterprise: Forensic triage and incident response], by Moser,
Andreas, and Michael I. Cohen. Digital Investigation, 2013.

link:https://storage.googleapis.com/docs.grr-response.com/distributed_forensics.pdf[Distributed forensics and incident response in the enterprise], by M.I. Cohen,
D. Bilby, G. Caronni. Digital Investigation, 2011.

Presentations
-------------

link:https://drive.google.com/file/d/0Bzniab0ILSg6RkdyUGZYOGtuX1U/view[GRR Meetup: GRR Users Meetup: Fleetspeak, API client, Go rewrite] @ Mar 2017 GRR Meetup by A. Moser, M. Bushkov, B. Galehouse, M. Lakomy. link:https://youtu.be/SIvf7-Lzp2M[Video].

link:https://drive.google.com/file/d/0BzuOLwDAeI1IaGZnbHJWSUhHXzg/view?pageId=113082118196076170073[GRR Meetup: 3.1.0 Release] @ Apr 2016 GRR Meetup by G. Castle and M. Cohen. link:https://youtu.be/SIvf7-Lzp2M[Video].

link:https://storage.googleapis.com/docs.grr-response.com/GRR%20Meetup-%20API%20Edition%20Nov%202015.pdf[GRR Meetup: API Edition] @ Nov 2015 GRR Meetup by G. Castle and M. Bushkov. Covers API basics and discusses where we are headed with API dev.

link:https://storage.googleapis.com/docs.grr-response.com/GRR%20Hunting%20for%20meetup%20Oct%202015.pdf[GRR Hunting Best Practices] @ Oct 2015 GRR Meetup by G. Castle.

link:https://storage.googleapis.com/docs.grr-response.com/ACSC%202015-%20Defending%20the%20Gibson%20in%202015.pdf[Tactical use of GRR Artifacts, Fuse, Plaso and Timesketch] by D. Bilby link:https://www.youtube.com/watch?v=JciAp0uB7AY[Demo Video (youtube)]

"link:https://storage.googleapis.com/docs.grr-response.com/OpenNSM_GRR_Presentation_Feb_2015.pdf[Intro to GRR]" for the Open Source Network Security Monitoring Group @ UIUC Feb 2015. link:https://www.youtube.com/watch?v=ZAXtCMspgY0[Video] by G. Castle

"link:https://storage.googleapis.com/docs.grr-response.com/GRR_Blackhat_2014_Greg_Castle.pdf[GRR: Find all the badness, collect all the things]" @ Blackhat 2014 link:http://www.youtube.com/watch?v=DudGrSv26NY[Video] by G.
Castle. Also presented link:https://youtu.be/eLehQ3QmdEA[a 20 min version of the same talk] for link:https://www.concise-courses.com/past/[Hacker Hotshots].

link:https://storage.googleapis.com/docs.grr-response.com/GRR%20Rapid%20Response%20-%20OSFC%202012.pdf[OSDFC 2012 GRR Overview], by D. Bilby

Workshops
---------

DFRWS US 2015 Workshop link:https://storage.googleapis.com/docs.grr-response.com/GRR_Workshop_DFRWS_US_2015.pdf[slides] and link:https://github.com/destijl/grr-workshop-setup[scripts to setup your own workshop infrastructure] by G. Castle.

DFRWS EU 2015 Workshop link:https://storage.googleapis.com/docs.grr-response.com/GRR%20DFRWS%20EU%20Workshop%202015%20Export.pdf[workshop slides] by A. Moser

OSDF 2013 link:https://storage.googleapis.com/docs.grr-response.com/GRR%20OSDF%20Workshop%202013.pdf[workshop presentation] and link:osdf2013workshop.adoc[materials] by D. Bilby.

Podcasts
--------

GRR Rapid Response on link:http://podcast.wh1t3rabbit.net/dtr-episode-98-grr-grr-rapid-response-0[Down the Security Rabbithole] Jun 2014 by G. Castle.

Whitepapers
-----------

link:https://storage.googleapis.com/docs.grr-response.com/GRR_Artifacts_Whitepaper_Blackhat2014_Greg_Castle.pdf[GRR Forensic Artifacts White Paper], by G. Castle

External Presentations
----------------------

These are presentations about GRR by people outside the core GRR team.

"link:https://github.com/pidydx/slides/blob/master/HumanHunting.pdf[Human Hunting]" @BSidesSF 2015 by Sean Gillespie. Covers how Yahoo is using GRR. link:https://www.youtube.com/watch?v=4qCvx3SnAm4[Video].

"link:http://kernsec.org/files/lss2015/GRR.pdf[GRR Rapid Response: Remote Live Forensics for Incident Response]" @ link:http://kernsec.org/wiki/index.php/Linux_Security_Summit_2015[Linux Security Summit] Aug 2015 by Sean Gillespie.
