= Getting Started =

This document describes getting a server and clients up and running for the first time. You have two options: 

 1. Run the link:https://registry.hub.docker.com/u/grrdocker/grr/[docker image built off the latest repository commit]. This is the fastest way to get a basic install up and running for testing, and gets you all of the latest features.
 2. Follow these instructions for an automated install on an Ubuntu system. This is a better option for stability and customization.
 
== Requirements ==

 * A linux box. At the moment the full install is thoroughly tested end to end on Ubuntu Server 14.04 64-bit footnote:[We don't provide a 32-bit server version since standing up new 32-bit linux servers is not something rational people do, and there are many places you can get 64-bit virtual servers for ~free.  We use the "amd64" notation, but this just means 64-bit, it runs fine on Intel.]. It works on other things fine footnote:[Older versions of Ubuntu will probably work fine, but you will at least need a newer version of the protobuf library.], but that is what it's tested on.
 * Recommend > 1GB Ram and a modern CPU if you want to run everything on one box
   (note that free Amazon EC2 instances don't have enough RAM).
 * Some machines (or VMs) to talk to the server. OSX, Windows and Linux agents are
   supported. Client and server can run on the same host for testing purposes.

== Install the Server ==

Download and run the installation script e.g. using wget:

---------------------------------------------------------------------------------------
wget https://raw.githubusercontent.com/google/grr/master/scripts/install_script_ubuntu.sh
sudo bash install_script_ubuntu.sh
---------------------------------------------------------------------------------------

*Note that the installation script requires bash to run and does not work with
plain sh.*

Once this completes successfully you should have a working server with an admin interface on port 8000, open it in your browser. You should also have grr_console in your path to interact via console.
   
== Install the Clients ==

The pre-packaged clients should be visible under Manage Binaries -> executables -> Windows -> installers. Download the client you need.

Run the client on the target machine as administrator:

 - For Windows you will see a 32 and 64 bit installer. Run the installer as admin 
   (it should load the UAC prompt if you are not admin). It should run silently 
   and install the client to  c:\windows\system32\grr\%version%\. It will also install 
   a Windows Service, start it, and configure the registry keys to make it talk to the 
   URL/server you specified during repack of the clients on the server.
 - For OSX you will see a pkg file, install the pkg. It will add a launchd item and start it.
 - For Linux you will see a deb and rpms, install the appropriate one. For testing purposes you can run the client
   on the same machine as the server if you like.

After install, hit Enter in the search box in the top left corner of the UI to see all of your clients that have enrolled with the server.
