= Release Notes =

Each release of GRR brings some significant changes as the project's code is
moving quickly. This section tries to identify the key changes and issues to
watch for when upgrading from one version to another.

== 3.0.0.2 to 3.0.0.3 ==

 - *WARN* A change to OpenSSL required us to sign our CSRs generated during the enrollment process. This wasn't necessary previously and provided no benefit for GRR so we had gained some speed by not doing it. Since new OpenSSL required it, we started signing the CSRs, but it meant that the 3.0.0.3 server will reject any 3.0.0.2 clients that haven't already enrolled (i.e. they will see a HTTP 406).  Old 3.0.0.2 clients that have already enrolled and new 3.0.0.3 clients will work fine. This basically just means that you need to push out new clients at the same time as you upgrade the server. 

== 0.2.9 to 3.0.0 ==

 - *WARN* After install of new deb you will need to restart the service
   manually.
 - *INFO* To get the new clients you will want to repack the new version with
   `sudo grr_config_updater repack_clients`. This should give you new Windows,
   Linux and OSX clients.
 - *INFO* Client themselves will not automatically be upgraded but should
   continue to work.

== 0.2-8 to 0.2-9 ==

 - *WARN* After install of new deb you will need to restart the service
   manually.
 - *WARN* Users have changed from being managed in the config file to being
   managed in the datastore. This means your users will not work. We haven't
   migrated them automatically, please re-add with `sudo grr_config_updater
   add_user <user>`
 - *INFO* To get the new clients you will want to repack the new version with
   `sudo grr_config_updater repack_clients`. This should give you new Windows,
   Linux and OSX clients.
 - *INFO* Client themselves will not automatically be upgraded but should
   continue to work.

= Config Variable Graveyard =

Sometimes config variables get renamed, sometimes removed. When this happens we'll try to record it here, so users know if local settings should be migrated/ignored etc.

You can verify your config with this (root is required to read the writeback config)
-----
sudo PYTHONPATH=. python ./run_tests.py --test=BuildConfigTests.testAllConfigs
-----

 * Client.confg: unused.  Now built from Client.config_hive and Client.config_key
 * Client.location: replaced by Client.control_urls
 * Client.config_file_name: unused
 * Client.package_maker_organization: replaced by ClientBuilder.package_maker_organization
 * AdminUI.team_name: replaced by Email.signature
 * Users.authentication: unused, user auth is now based on aff4:/users objects. Use config_updater to modify them.
 * Nanny.nanny_binary: replaced by Nanny.binary
 * NannyWindows.* : replaced by Nanny.
 * Email.default_domain: essentially duplicated Logging.domain, use that instead.
 * Worker.task_limit: unused
