= GRR Project Roadmap =

This roadmap (updated Q1 2014) reflects the current focus of the core GRR
development team and the pieces of work that have current active development.

== Current Active Work (Q1-Q2 2014) ==
 * *UI simplification* One right way to do things, with less options for
   shooting yourself in the foot when scheduling work.
 * *Memory collection and analysis* Move from volatility to the new
   link:https://code.google.com/p/rekall/[rekall] framework to streamline and
   enhance memory analysis capabilities.
 * *Data interchange and export* Improved export capabilities for interchanging
   data with other systems.
 * *Shared artifacts support* Extending the existing artifact framework to
   support many new parsers and provide means to interchange these with other
   projects like link:https://code.google.com/p/plaso/[plaso] and
   link:https://code.google.com/p/rekall/[rekall].

== Next Up ==
 * *Timelining Integration* log2timeline python (plaso) including extending and
   reworking collection support.
 * *Anomaly detection* Automated server side processing of artifacts to
   automatically detect anomalies.
 * *Baselining* Work on building out the framework to support snapshots and
   analysis of various pieces of data to allow for comparison across a fleet and
   across time.


Because there are a number of developers working on extending individual parts
of GRR, there may well be significant other pieces of work going on, checking
the dev list is probably your best option if you want an up to date picture of
that.
