= Building GRR From Scratch =

:toc:
:toc-placement: preamble
:icons:

*Note*: This page contains information about building the GRR server from
scratch. You probably want the link:quickstart.adoc[Quickstart Instructions]
instead of this document.

The quickstart script largely installs prebuilt debs from the link:launchpad.net/~gift[GIFT PPA]. If you'd prefer to get the dependencies from original sources yourself or install on a non debian/ubuntu system you should first consider whether link:https://github.com/google/grr-doc/blob/master/docker.adoc[using Docker] might suit your needs. If not, start with the vagrant link:https://github.com/google/grr/blob/master/vagrant/install_linux.sh[client build environment install script].  This gets you all of the more complex dependencies. From there you need to:

Install the remaining server python requirements:
-------------------------------
sudo pip install -r requirements.txt
-------------------------------

Then install GRR, and follow any further instructions from the script:
----
sudo bash scripts/install_server_from_src.sh
----

The UI server listens on 127.0.0.1:8080 by default. See the link:https://github.com/google/grr-doc/blob/master/troubleshooting.adoc[troubleshooting section] if you have problems running the services.
