= Troubleshooting =

The many different steps makes the GRR server installation process susceptible to errors. Here some common issues and solutions are described.

== ImportError: cannot import name jobs_pb2 or similar ==

If you see "ImportError: cannot import name jobs_pb2" or a similar error for any other _pb2 file, you need to regenerate the protobuf files.  Just run
-------------------------------------------------------
python setup.py build
sudo python setup.py install
-------------------------------------------------------

== The upstart/init.d scripts show no output ==

When I run an init.d script e.g. "/etc/init.d/grr-http-server start" it does not show me any output.

Make sure that the "START" parameter in the corresponding default file, e.g. "/etc/default/grr-http-server", has been changed to "yes".

== I cannot start any/some of the GRR services using the init.d scripts ==

When it run an init.d script e.g. "/etc/init.d/grr-http-server start" it indicates it started the service although when I check with "/etc/init.d/grr-http-server status" it says it is not running.

You can troubleshoot by running the services in the foreground, e.g. to run the HTTP Front-end server in the foreground:
-------------------------------------------------------
sudo grr_server --start_http_server --verbose
-------------------------------------------------------

== Any/some of the GRR services are not running correctly ==

Check if the logs contain an indication of what is going wrong.

Troubleshoot by running the services in the foreground, e.g. to run the UI in the foreground:
-------------------------------------------------------
sudo grr_server --verbose --start_ui
-------------------------------------------------------

== Cannot open libtsk3.so.3 ==

error while loading shared libraries: libtsk3.so.3: cannot open shared object file: No such file or directory

The libtsk3 library cannot be found in the ld cache. Check if the path to libtsk3.so.3 is in /etc/ld.so.conf (or equivalent) and update the cache:
-------------------------------------------------------
sudo ldconfig
-------------------------------------------------------

== MongoDB won't start ==

Check the MongoDB log for any indication why it won't start. Default location:
-------------------------------------------------------
/var/log/mongodb/mongodb.log
-------------------------------------------------------

== Fixing out of disk with mongo ==

This is hard on a bunch of ubuntu boxes because /etc/mongodb.conf variable dbpath is not honored in some cases. Simple fix is:

-------------------------------------------------------
sudo service mongodb stop
sudo mkdir /mnt/mongodb
sudo chown -R mongodb /mnt/mongodb
sudo mv /var/lib/mongodb/* /mnt/mongodb/
sudo ln -s /mnt/mongodb /var/lib/mongodb
sudo chown -R mongodb:nogroup /mnt/mongodb/
sudo service mongodb start
-------------------------------------------------------

== Cron Job view reports an error ==

Delete and recreate all the cronjobs using GRR console:
-----------------------------------------------------------------------
aff4.FACTORY.Delete("aff4:/cron", token=data_store.default_token)
from grr.lib.aff4_objects import cronjobs
cronjobs.ScheduleSystemCronFlows(token=data_store.default_token)
-----------------------------------------------------------------------

== Protobuf 2.5.0 ==

GRR only works with the Protobuf library v2.5.0 or newer. If your distribution
comes with an older version, follow the instructions below:

Remove any version of protobuf that is older than 2.5.0.

Note that this will also remove a couple of dependencies:

-------------------------------------------------------
sudo apt-get remove libprotobuf python-protobuf
-------------------------------------------------------

To build Protobuf from source, install the following packages on a Debian-based
system:

--------------------------------------------------------------------
sudo apt-get install build-essential uuid-dev zlib1g-dev python-dev
--------------------------------------------------------------------

Download protobuf version 2.5.0 or later from link:http://code.google.com/p/protobuf/[protobuf]

Extract the package:
-------------------------------------------------------
tar xfv protobuf-2.5.0.tar.gz
cd protobuf-2.5.0
-------------------------------------------------------

Build and install libprotobuf:
-------------------------------------------------------
./configure --prefix=/usr/
make
sudo make install
sudo ldconfig
-------------------------------------------------------

Build and install the Python bindings:
-------------------------------------------------------
cd python
python setup.py build
python setup.py test
sudo python setup.py install
-------------------------------------------------------
