= Building The Windows Client =

Windows licensing means we can't just simply provide a build vm via vagrant as
we've done for linux.  So there's more hoops to jump through here, but it's as
automated as possible.

== Client Build VM ==

First, install link:https://www.vagrantup.com/[Vagrant],
link:https://packer.io/[Packer], and VirtualBox.  See
link:http://ilostmynotes.blogspot.com/2015/04/vagrant-packer-and-boxcutter-ftw-create.html[here]
for some background on these technologies. Then checkout boxcutter:

---
git clone https://github.com/boxcutter/windows.git boxcutter-windows
---

and make a base windows VM. If you have access to corporate ISOs, follow the
boxcutter instructions (by creating Makefile.local) to point to these and save
yourself Windows activation hassles later on.

---
cd boxcutter-windows
make virtualbox/eval-win7x64-enterprise
---

Then tell vagrant it's there:
---
cd ~/grr/vagrant
vagrant box add ~/boxcutter-windows/box/virtualbox/eval-win7x64-enterprise-nocm-1.0.4.box --name windows_7_64_vanilla
---

Bring it up with:

---
vagrant up windows_7_64_vanilla
---

and get it started on all the windows updates. You need to at least get it past
SP1 to be able to install Visual Studio.  It will probably take about 25 min and
require a reboot or three (which is why we can't script this effectively).

Once windows update is happy, run this to get all the big, slow stuff installed
(40min):

---
C:\grr\vagrant\windows\install_visual_studio.bat
---

Once that finishes you have a base VM that won't need updating, and can be used
to build from if dependencies change. You'll want to do your windows activation
now if you haven't already, and running a disk cleanup will save you some
copying time later, the service pack install alone creates 500MB of backup
files. Shut it down then save it as it's own vagrant vm (45 min, it's now a 12G
VM):

---
VBoxManage list vms
vagrant package --base "<Windows vm name>" --output windows_7_64_base
vagrant box add windows_7_64_base --name windows_7_64_base
vagrant destroy windows_7_64_vanilla
---

Bring up the new one. Note that when dependencies change you'll only need to do
these final steps again to get an updated environment:

---
vagrant up windows_7_64_base
---

Finish installing dependencies with (30 min):

---
C:\grr\vagrant\install_windows.bat
---

And save your final build VM with:
---
VBoxManage list vms
vagrant package --base "<Windows vm name>" --output windows_7_64
vagrant box add windows_7_64 --name windows_7_64
vagrant destroy windows_7_64_base
---

