mysql_data_source_name: "fleetspeak-user:fleetspeak-password@tcp(mysql-fleetspeak:3306)/fleetspeak"
https_config: <
  listen_address: "0.0.0.0:9090"
  certificates: "FRONTEND_CERTIFICATE"
  key: "FRONTEND_KEY"
  frontend_config: <
    https_header_checksum_config: <
      client_certificate_header: "x-client-certificate" 
      client_certificate_checksum_header: "x-client-cert-hash"
    >
  >
>
health_check_config: <
  listen_address: "0.0.0.0:8080"
>
notification_listen_address: "0.0.0.0:12000"
notification_public_address: "fleetspeak-frontend:12000"
